### ISSUE TITLE
Support Linux & macOS builds

### ISSUE THREAD

**Issue by mtobeiyf** [mtobeiyf/pile#11]
Build and test under Linux & macOS. 
Release corresponding binaries.

**Comment by mtobeiyf** [comment]
Builds are available in [v0.2.2](https://github.com/mtobeiyf/pile/releases/tag/v0.2.2)
Notice that they are built with CI, so I **haven't tested it**. Just released. 
If you encounter any problems, open an issue and I'll look into it.

macOS: zip, dmg
Linux: AppImage

**Comment by pcause** [comment]
just installed on ubuntu 18.04 beta and did a few operations.  seems to work.  it satys in the indicator area after I close the window which is NICE.  dragging web links worked.

**Comment by ruipimentel** [comment]
Me too. Just installed on a Fedora 25 via AppImage and it looks very nice, thank you! :)

**Comment by mtobeiyf** [comment]
Linux and macOS builds are now supported with release [v0.3.0](https://github.com/mtobeiyf/pile/releases/tag/v0.3.0)
Including lots of fixes on macOS
