### ISSUE TITLE
Let user specify location for the data

### ISSUE THREAD

**Issue by pcause** [mtobeiyf/pile#12]
Can you add something so that I can specify a directory where you'll store my "piles"?  If you do this then there are any number of sync'ing tools that users can use to backup their data and copy to multiple machines.

**Comment by mtobeiyf** [comment]
@pcause Hi, 
thank you.
A good idea to give users the right to choose their data storage path. 
I'll see if I could make it robust enough so there won't be any unpredictable things happen.
You can expect this functionality to come in the near future. 😃

**Comment by valdotdev** [comment]
Would this also mean that when I set the location (mac version) on my dropbox, after it syncs I can use the same location and use it on my Windows machine? Just sayin' :wink:

**Comment by mtobeiyf** [comment]
You can customize your storage path with https://github.com/mtobeiyf/pile/commit/54114cfbc98eba46be8aac2f929e702b90b79e0b
