### ISSUE TITLE
ability to modify the font and other elements

### ISSUE THREAD

**Issue by pcause** [mtobeiyf/pile#16]
I have a 4k screen.  the font in pile looks tiny.  also when I enter code in the notes box the color/style makes it barely visible.

Can we have a command to set base font and size?  Just size would be good to start.

For future, having the ability to import theme files, created for pile, or perhaps used by other editors/electron projects/atom or vs code?? would be good.

**Comment by pcause** [comment]
ok, the reload did the trick. 

thanks for the font.

understand keeping it simple.  perhaps just allow an adnaced user to specify an extra stylesheet you load last so they can override certain things.

**Comment by mtobeiyf** [comment]
Add an extra stylesheet is feasible~ Thanks for the idea.
It would make the "theme system" and fontsize setting much easier.

**Comment by pcause** [comment]
Ok, I have an idea for this.  Create a section in the json and the base stylesheet goes in this section of the json.  When I create a board, the board has a hidden section of json for the stylesheet.  when you load a board you load the stylesheet for the board from the jason for that board.  You then add a command to edit the stylesheet and save back to the json, just like a note.  also a way to copy the base stylesheet into any board in case one screws it up.  now every board can be styled off a base stylesheet that is part of the json describing the board

**Comment by mtobeiyf** [comment]
Thanks for the idea. Seems great.
I'll investigate and see if such behavior could be realized in a proper way.

**Comment by mtobeiyf** [comment]
A few lines of css and an **ugly** version of Dracula theme, bang! 🦇 
![image](https://user-images.githubusercontent.com/5097752/38325288-295113a8-3875-11e8-8332-d3c6fffb1f9e.png)
I'll figure how to make it customizable and easy to switch to 😄 
So you can tune the theme by yourselves.

**Comment by mtobeiyf** [comment]
@pcause  Injecting custom style file is supported in commit https://github.com/mtobeiyf/pile/commit/9fb11cd531aee3f5c43b3ac1ef46ef805e8f62d4 in the dev branch.
Simply create a `style.css` file under the user data path same as `db.json`, then it will be automatically loaded.
The only inconvenience is that you have to manually inspect the elements and write the css rules.
But I'll provide templates or examples like the 'Dracula theme' above.

@ClaudiuCeia Check this.

**Comment by pcause** [comment]
thanks and awesome

**Comment by mtobeiyf** [comment]
With the release [v0.3.2](https://github.com/mtobeiyf/pile/releases/tag/v0.3.2), you are able to customize the style.

Here, I provide an example:
1. Go to the `settings` -> `Advanced` -> `Storage Path` -> `Open Storage Path`, it will take you to your default storage path
2. Place a `style.less` in that directory, the style file will be automatically loaded.

[style.zip](https://github.com/mtobeiyf/pile/files/1976815/style.zip)
This is an incomplete style file. If you are interested, try it out.

**Comment by iursevla** [comment]
@mtobeiyf  thanks

Are you planning to add the possibility to add colors to each note? A menu with some colors after 
Edit and Delete for each note would be good.

**Comment by mtobeiyf** [comment]
@iursevla Hi, excuse me that I don't get your point. What's the color for? Could you provide me with examples or some scenario where this would be useful. I'll add that if it's reasonable. Thank you.

**Comment by iursevla** [comment]
@mtobeiyf  
Color for each [todo item ](https://i.imgur.com/8oMV32A.png) for example. This way i could separate the TODOs by some specific characteristic. 
I don't know if more people would want/need this or if it's too specific for my needs.

**Comment by iursevla** [comment]
@mtobeiyf 
Thanks for your hard work
If i find myself with some free time i'll see what I can contribute for this project.
