### ISSUE TITLE
[macOS] JavaScript error when first time launching the app

### ISSUE THREAD

**Issue by valdotdev** [mtobeiyf/pile#17]
Hi! 
My system: `macOS High Sierra 10.13.3`
Pile ver.: `0.2.2`
When opening the app for the first time, an error pops up.
![screen shot 2018-03-24 at 9 14 48 pm](https://user-images.githubusercontent.com/17805772/37864391-e889a4a4-2fa8-11e8-9abb-09229fee0500.png)
Then I need to manually quit the app.
Goes away on subsequent launching of the application.

**Comment by mtobeiyf** [comment]
Same problem occurs both on the released app and during the build procedure.
I'm still looking into it, cause it doesn't appear the second time I run the app.

Another problem is the dropped item doesn't show their icon properly. 

It will be fixed as soon as I borrowed a Mac 😂

**Comment by valdotdev** [comment]
Awesome. Thanks!

**Comment by mtobeiyf** [comment]
Fixed with commits https://github.com/mtobeiyf/pile/commit/627defc8a9fb2704e2a8e35e0d2566525f7bece3 and https://github.com/mtobeiyf/pile/commit/bb0ccf6e3676f2e0bc07f5e253908d506ac144a9
