### ISSUE TITLE
[macOS] Large Pile menu bar icon

### ISSUE THREAD

**Issue by valdotdev** [mtobeiyf/pile#18]
Hi,
My system: `macOS High Sierra 10.13.3`
Pile ver.: `0.2.2`
This is only visual, but very distracting.
![screen shot 2018-03-24 at 9 15 47 pm](https://user-images.githubusercontent.com/17805772/37864427-95981bee-2fa9-11e8-8768-493d6883de9e.png)

**Comment by mtobeiyf** [comment]
Hi, @valdotdev 
Thanks for the feedback. 👍 
I'll fix it as soon as possible.

**Comment by valdotdev** [comment]
Take your time. Loving the app so far! 👍

**Comment by mtobeiyf** [comment]
@valdotdev Fixed with commit https://github.com/mtobeiyf/pile/commit/2f86dff734c75535edc47420b5a977d0907f7701

![2018-03-25 00 31 04](https://user-images.githubusercontent.com/5097752/37866343-699028d2-2fc4-11e8-9ab7-22df6d6aa97d.png)
