### ISSUE TITLE
[macOS] Unrecognized icons in App/File hub

### ISSUE THREAD

**Issue by valdotdev** [mtobeiyf/pile#20]
I'm not sure if this is known or just on Mac, but whenever I add a file to the App/File hub, the icons are not displayed correctly or its unrecognized (regardless of file type). For apps, it shows **folders**.
![screen shot 2018-03-26 at 11 26 29 pm](https://user-images.githubusercontent.com/17805772/37915983-486afb2a-314d-11e8-9547-b420341d8856.png)
`System: macOS 10.13.3 High Sierra`
`Pile ver.: 0.2.2`

**Comment by mtobeiyf** [comment]
Thanks, 
This is a bug I mentioned in https://github.com/mtobeiyf/pile/issues/17

Now, I'm striving to setting up an macOS virtual machine on my Surface Pro...
I'll fix this soon

**Comment by valdotdev** [comment]
Oh sorry must've missed that bit there. Many thanks!

**Comment by mtobeiyf** [comment]
That's alright. Otherwise, I will open a issue of this bug. 
Thank you. 😄

**Comment by mtobeiyf** [comment]
@valdotdev It must be better now, hah. 😸  https://github.com/mtobeiyf/pile/commit/b117b22dc7857ec2541ab49b85f888ead13a1b1a

![2018-03-26 9 28 04](https://user-images.githubusercontent.com/5097752/37946885-d9482818-313c-11e8-9e97-21e71131bdf9.png)
Will release soon.

**Comment by valdotdev** [comment]
Thanks for your hard work! 👍
