### ISSUE TITLE
[macOS] Pasting on any textbox/input field in Pile does not work.

### ISSUE THREAD

**Issue by valdotdev** [mtobeiyf/pile#21]
Only tested on `macOS 10.13.3 High Sierra` but pasting does not work on any texbox or field in the app even within settings.
Using `Pile ver:. 0.2.2`
A little problematic when you need to paste a bunch of text or code in fields such as the `Todo` or `Notes` hub.

**Comment by mtobeiyf** [comment]
Solved with commit https://github.com/mtobeiyf/pile/commit/d823f7e6c4b9958d791f1ad3d777b0318ca1dd8d
