### ISSUE TITLE
idea: grid/spreadsheet hub

### ISSUE THREAD

**Issue by pcause** [mtobeiyf/pile#25]
It would be nice to have a grid/spreadsheet hub.  There are a bunch of components here https://jspreadsheets.com/ that might do all of the work.  There which work with Vure.  There is this one:  a "getting started" for Vue -https://www.ag-grid.com/best-vuejs-data-grid/ and this one https://jspreadsheets.com/vue-handsontable-official.html which has a nice example.

**Comment by mtobeiyf** [comment]
It would be better if you could provide me with a detailed scene where this component is useful and needed, rather than creating a `xlsx` spreadsheet, which can be handled both on Windows and Linux with Excel or LibreOffice.

**Comment by pcause** [comment]
it is the ability to embed a basic spreadsheet capability so if I am working on a project I have notes, calculations, links, etc all together.  tables in markdown are OK for display but this allows me to do some basic calculation and formulas and you have to have the table data already done.  for example do a quick project costing right in the board or do a quick sprwadsheet to calculate possible car payments for an interest rate and price while researching a car purchase.  all of my data is in one palce in the Board.  .  you'd save/load the data in json just like other hubs.

**Comment by valdotdev** [comment]
@mtobeiyf Just to add to markdown tables, I'm having trouble with cells and data in terms of organization and alignment. It would be appreciated if it was a bit more refined and maybe add actual table borders. :)

**Comment by mtobeiyf** [comment]
@valdotdev I noticed it and I'm going to solve it soon.

**Comment by valdotdev** [comment]
@pcause I see where you're going but implementing even a basic spreadsheet hub is quite a task considering various formulas needed. Either the app would support 3rd party modules/components to get the job or wait a while for the dev to implement something like this from scratch in which you could just. Notes/notepad aside, for me, if you already have something as comprehensive as a spreadsheet tool like Excel that you could just drag and drop into a hub then at the very least this feature won't be a priority. Of course that just my opinion. Who knows maybe @mtobeiyf can get it done in no time. :wink:

**Comment by pcause** [comment]
I think you are incorrect as there are components that do all the work that can be plugged in.  Data is saved in json.  Looking for basics not full blown excel.  But @mtobeiyf is the author and does the work so his call.

**Comment by mtobeiyf** [comment]
I kinda agree @valdotdev that the spread sheet hub is not a priority. (Cause I need to solve bugs in the markdown note hub first 😂 
There is spreadsheet component. But in which way should it be integrated needs further consideration. 🤔 @pcause 
This project is just begining, the primary work now is to make it more robust and extensible. 😄

**Comment by mtobeiyf** [comment]
@valdotdev Customized Github-Flavored-Markdown style is introduced into the note section, the tables should be displayed normal now, with the commit https://github.com/mtobeiyf/pile/commit/46de10c350135539967f30dff44286237ad980ba in dev branch.

![image](https://user-images.githubusercontent.com/5097752/38778663-b5f2d0ee-40ef-11e8-8e22-4d9d71850886.png)

**Comment by valdotdev** [comment]
Nice! I can now properly tidy-up a bunch of my notes. Thanks!

**Comment by mtobeiyf** [comment]
Closing this as it's not a necessity right now. 
The [new release](https://github.com/mtobeiyf/pile/releases/tag/v0.3.2) supports right table style.
