### ISSUE TITLE
Sub Item To-do

### ISSUE THREAD

**Issue by Hudison** [mtobeiyf/pile#26]
Hi, I'm not very experienced with JavaScript and I've been having bad experiences with this type of application, but Pile has conquered my heart. My idea is to be able to create one or more "Sub To-do" (I do not know if it's the right name, sorry). For me, this will be a great resource, because when I'm programming or studying, I'd like to stay organized. The "Sub To-do" is fantastic for this, because I know exactly what I have to do and what dependencies I need.
I imagine myself trying to implement this because I would love to contribute with a project, even one as good as this. I do not know how long it would take or if they are already developing it, but I think it would be a big step for my learning. Thank you very much and sorry about my English.

**Comment by mtobeiyf** [comment]
Thank you 😄 
You can contribute to this with your own effort. Contributing is welcome! 
Is a sub todo like this?
```
- a
  -b
- c
  -d
```
Fork this project and develop by yourself. The source code is not that complicated.
If you have any questions, just ask me

**Comment by Hudison** [comment]
Yep, but with more sub itens like this:
- a
  - b
     - c
       - n...
Thank you, i will do my best.

**Comment by mtobeiyf** [comment]
Got it, you need to modify the todo component, also the data storage.
Actually, note card with markdown can create simple task list with more flexible additional information.
![image](https://user-images.githubusercontent.com/5097752/38267320-b36be5c2-37ad-11e8-8343-e7959c3accba.png)

（a bit ugly, though

**Comment by mtobeiyf** [comment]
Closing this temporarily
Making a contribution is always welcome 😃
