### ISSUE TITLE
[Feature Request] [macOS] Quit shortcut (CMD+Q) and exit confirmation pop-up

### ISSUE THREAD

**Issue by valdotdev** [mtobeiyf/pile#28]
Just a small feature request from me. A shortcut to quit the application (CMD+Q) would be nice.

In addition, an optional toggle in settings when quitting the app (some users doesn't any pop-ups), a pop-up or dialogue box will appear to confirm if you really want to exit the application to avoid accidentally quitting.

Thanks!

**Comment by mtobeiyf** [comment]
I'll add shortcut support for both quiting and toggling the application to the front in the next version.
Currently, the app would hide to tray when you click the 'x'. 
A dialog prompt is good, I'll figure out how to realize it.

(actually, I don't want users to completely quit it though 😂  haha

**Comment by valdotdev** [comment]
Thanks!

> (actually, I don't want users to completely quit it though :joy: haha

Fair enough :laughing:

**Comment by mtobeiyf** [comment]
Shortcut to quit the app https://github.com/mtobeiyf/pile/commit/72b0b18097940efe1391f3c7feb3e7ad75617174 in the dev branch
Cmd+Option+Q  (Ctrl+Alt+Q)
It's not a global shortcut, only enabled when the window is activated.
I don't think a confirmation is needed cause the app is so 'hard' to quit 😂

**Comment by mtobeiyf** [comment]
Temporarily, a confirm dialogue is not too necessary, thus I'm not going to add it right now.
By the way, I change the shortcut to 'Cmd+Q'
It will soon appear in the next release. 😃
