### ISSUE TITLE
New logo design for the project

### ISSUE THREAD

**Issue by Arslanshn** [mtobeiyf/pile#8]
merhaba projen için tamamen ücretsiz yeni logo tasarlamak istiyorum.

**Comment by Arslanshn** [comment]
Hi, I want to design a new logo for the project completely free...

**Comment by mtobeiyf** [comment]
Hi, @Arslanshn 
Thank you.
Feel free to design a new logo 😃 It's an open source project. 
Just comment under this issue and we can further discuss.
Also, any suggestion is welcome.

**Comment by mtobeiyf** [comment]
Close for now.
If you came up with a new design, I will reopen this.
