### ISSUE TITLE
drag url's (really any URI) to apps/files

### ISSUE THREAD

**Issue by pcause** [mtobeiyf/pile#9]
If I go to the address bar (firefox) and highlight and drag the URL to the apps/files pane of pile nothing happens.  I'd expect you to be able to let me drop any URI to the apps/files area.

**Comment by mtobeiyf** [comment]
Thanks,
It's a good idea.
But I need to further investigate if the framework (Electron) support this kind of drag and drop behavior.
I'll make an update if it supports.

**Comment by mtobeiyf** [comment]
@ClaudiuCeia  Added in this commit https://github.com/mtobeiyf/pile/commit/004b5d4ea5b69e253b635164001f2243f9161fc2

And it will appear in the **next release**.
Any suggestions are welcome.
![link](https://user-images.githubusercontent.com/5097752/37694741-81f9c512-2d04-11e8-81f7-ceae6d668613.gif)

**Comment by pcause** [comment]
Thanks.  Looking forward to a release with this.

**Comment by mtobeiyf** [comment]
@pcause  Released with v0.2.2 https://github.com/mtobeiyf/pile/releases/tag/v0.2.2
Check it out.
